services:
  testpoint:
    build:
      context: ./testpoint
    container_name: testpoint
    networks:
      - mxc-net
    volumes:
      - "../testpoint:/testpoint"  # Volume pour le script de test
    tty: true

  backend-js:
    build:
      context: ./backend-js
    container_name: backend-js
    networks:
      - mxc-net
    ports:
      - "7070:7070"
    volumes:
      - "../DATA/content:/content"
    environment:
      - NODE_ENV=production

networks:
  mxc-net:
    driver: bridge
