services:
  testpoint:
    image: tacia-testpoint
    build:
      context: ./testpoint
      dockerfile: Dockerfile
    container_name: testpoint
    networks:
      - tacia-net
    volumes:
      - "../testpoint:/testpoint"  # Volume for test script
    environment:
      - BACKEND_SERVICE=${BACKEND_SERVICE}
    tty: true

  backend-js:
    image: tacia-backend-js
    build:
      context: ../backend-js
      dockerfile: Dockerfile
    container_name: backend-js
    networks:
      - tacia-net
    # ports:
    #   - "7070:7070"
    volumes:
      - ${CONTENT_DIR_HOST}:/content
    environment:
      - NODE_ENV=production

  backend-java:
    image: tacia-backend-java
    build:
      context: ../backend-java
      dockerfile: Dockerfile
    container_name: backend-java
    networks:
      - tacia-net
    # ports:
    #   - "7070:7070"
    volumes:
      - "${CONTENT_DIR_HOST}:/content"
    environment:
      - JAVA_OPTS=-Xmx512m

  frontend:
    image: tacia-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - tacia-net
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BACKEND_SERVICE=${BACKEND_SERVICE}


networks:
  tacia-net:
    driver: bridge
