services:
  testpoint:
    image: tacia_testpoint
    build:
      context: ./testpoint
      dockerfile: Dockerfile
    container_name: tacia_testpoint
    networks:
      - tacia_net
    volumes:
      - "../testpoint:/testpoint"  # Volume for test script
    environment:
      - BACKEND_SERVICE=${BACKEND_SERVICE}
    tty: true

  backend-js:
    image: tacia_backend_js
    build:
      context: ${BACKEND_PATH:-../backend-js}
      dockerfile: Dockerfile
    container_name: tacia_backend_js
    networks:
      - tacia_net
    # ports:
    #   - "7070:7070"
    volumes:
      - ${CONTENT_DIR_HOST}:/content
    environment:
      - NODE_ENV=production

  backend-java:
    image: tacia_backend_java
    build:
      context: ${BACKEND_PATH:-../backend-java}
      dockerfile: Dockerfile
    container_name: tacia_backend_java
    networks:
      - tacia_net
    # ports:
    #   - "7070:7070"
    volumes:
      - "${CONTENT_DIR_HOST}:/content"
    environment:
      - JAVA_OPTS=-Xmx512m

  frontend:
    image: tacia_frontend
    build:
      context: ${FRONTEND_PATH:-../frontend}
      dockerfile: Dockerfile
    container_name: tacia_frontend
    networks:
      - tacia_net
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BACKEND_SERVICE=${BACKEND_SERVICE}


networks:
  tacia_net:
    name: tacia_net
    driver: bridge
