services:
  testpoint:
    build:
      context: ./testpoint
      dockerfile: Dockerfile
    container_name: testpoint
    networks:
      - tacia-net
    volumes:
      - "../testpoint:/testpoint"  # Volume for test script
    tty: true

  backend-js:
    build:
      context: ../backend-js
      dockerfile: Dockerfile
    container_name: backend-js
    networks:
      - tacia-net
    ports:
      - "7070:7070"
    volumes:
      - "../DATA/content:/content"
    environment:
      - NODE_ENV=production

  backend-java:
    build:
      context: ../backend-java
      dockerfile: Dockerfile
    container_name: backend-java
    networks:
      - tacia-net
    ports:
      - "7070:7070"
    volumes:
      - "../DATA/content:/content"
    environment:
      - JAVA_OPTS=-Xmx512m

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - tacia-net
    ports:
      - "80:80"
      - "443:443"

networks:
  tacia-net:
    driver: bridge
